version: "3.9"
services:
  python:
    tty: true # Enables debugging capabilities when attached to this container.
    image: python:3
    container_name: exercism_python
    volumes:
      - '.:/usr/src/app'
# docker compose --verbose up -d
# docker exec -it exercism_python bash